[package]
name = "afs-indegene"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
members = [
    "afs-cli",
    "afs-daemon",
]

[[bin]]
name = "afs-cli"
path = "afs-cli/src/main.rs"

[[bin]]
name = "afs-daemon"
path = "afs-daemon/src/main.rs"

[dependencies]
actix-web = "4.3.1"
calamine = "0.19.1"
clap = { version = "4.2.7", features = ["derive"] }
deadpool-lapin = "0.10.0"
lapin = "2.2.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.1", features = ["full"] }
toml = "0.7.3"
zip = "0.6.5"
