[package]
name = "afs-api-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
ssh2 = "0.9.4"
uuid = { version = "1.3.4", features = ["v4"] }